nginx:
  build: .
  ports:
    - 80:80

transient:
  image: theconnman/transient
  ports:
    - 8080:3000

youtransfer:
  image: remie/youtransfer:stable
  ports:
    - 8081:5000

mongo:
  image: mongo

rocketchat:
  image: rocketchat/rocket.chat:latest
  ports:
    - 8082:3000
  links:
    - mongo:mongo
